= Kris Nova suggested AsciiDoc

_Thursday, January 9, 2025, 12:00:59AM EST_

I get asked a lot why I use AsciiDoc now, and I have written extensively about justifying the decision from a technical point of view. However, I want to focus on how I learned about it from Kris Nova for a second.

I was obsessed with getting the simplest, most standardize format for knowledge content so that it would not get out of date. Little did I know the AI revolution would entirely blow up the Zettelkasten model, but that's covered elsewhere.

It was during that time that Kris noticed I was focused on Markdown. I think, actually, that I was watching her work on her _Hacking Capitalism_ book and I might have started the conversation in the chat. She didn't attack me or my selection of Markdown. She just used AsciiDoc and mentioned that it had been recommended to her by other published authors since O'Reilly and other reputable publishers used it a lot for tech books—especially since it has full support for LaTeX (not just for math). I looked into it and saw the use of in-code references that are bulleted below, which I have seen in dozens of books I have read, and it was immediately obvious that this was the choice _specifically for book publishing_.

The more I looked at the syntax the more annoyed I got. And Ruby? Really?

Here's the thing, though, it is and was the best tool for the publishing job. There is nothing that even holds a candle to it. Everything else tries to be it—even Pandoc—but they all fail.

This was really hard to accept. I knew it was the right tool, but had invested so much time and energy into using Markdown. I even created PEGN to create my own meta-language grammars on top of Markdown that simplified it further with the hope of making it all the more approachable by the masses. I was wrong.

Markdown is absolutely amazing for `README.md` files and the like, or even chatting in Discord, but it does not specify something as basic and rudimentary as including other files—even from remote URI sources. AsciiDoc had all that on the first day because that is the problem it was trying to solve for writers, not simple `README.md` writers and note takers. AsciiDoc is complex but it is also very highly specified. Any Markdown variation that would allow the same requirements is not.

To get a sense of this, look at how MkDocs and Obsidian have bastardized Markdown in ways that no other variation will accept rendering them completely unable to be used by any other parser. AsciiDoc has _never_ had this problem.

The conclusion is that because I had made a friend who had written a book and actually had it published I was able to cut through the hype and influencer conjecture on the Internet and learn the _real_ tool for the job from someone who _has had that job_. I will be forever grateful to Kris for being so kind and patient about her corrections—if I can even call them that. Hopefully I can become more like her. I miss her so much.
