= More Mormon insanity

_Friday, January 3, 2025, 1:21:56PM EST_

Thanks to the amazing couple over at https://www.youtube.com/@alyssadgrenfell I have both been triggered into a massive panic attack around Christmas and had a cathartic laugh at a near 90-year-old "Prophet" attempt to explain his face in a hat while "translating" the Book of Mormon.

== Mormon cultists lie about translations of book of Mormon

When I read this in Rough Rolling Stone it sent me on my path of doubt/reality check that led me to leave the church. I now see what good company I was in.  Tom Phillips, a life-long faithful member who was chosen to have his "calling and election made sure" did a full interview chronicling his story. It was heart-wrenching to read all 102 pages of the transcript PDF—especially the absolutely inexcusable, shameful response from Jeffery Holland, a man I have come to strongly and deeply despise for his regular referral to anyone _not_ believing exactly as he does as unintelligent, evil, or just plain stupid.

All Tom did is ask honest, simple questions that were met with the same hostility that caused Joseph Smith to illegally destroy a printing press publishing _facts_ about Joseph that the church to this day calls "lies".

== Secret ceremony I never knew

I was pretty high up in the church, or so I thought. Turns out over 20,000 people since the time of Joseph Smith have had an "apostle" wash their feet and basically tell them they cannot do anything that would keep them out of heaven except murder someone. If I hadn't known about a single other thing I would have left the church just over that absolute bullshit.

== Gross mutilation of own body in covenants

The temple ceremony where I promised to remove my bowels and innards and slit my throat rather than talk about the temple ceremony wasn't even the most gruesome. They used to really have to add horrible language. Thank GOD for the Internet. The penalties have been completely removed from the ceremony now. I guess God changes to meet the times.

== I can only take so much

The more I keep learning about just how horribly the Mormon cult is, the more I wish I had left it without collapsing and falling in love with another woman who loved me for me and not because I was Mormon. Tom's story _proves_ that you can be absolutely the most righteous Mormon on planet Earth and _still_ have your wife leave you and think you are scum in Satan's power. The Mormon church is thankfully dying slowly but surely behind the scenes and it could not bring me more joy.

== References

- https://www.mormonstories.org/tom-phillips-and-the-second-anointing/
- https://www.youtube.com/@alyssadgrenfell
- https://youtu.be/W_eSubCKmGo
- https://youtu.be/8tqLad2Jse4
- https://youtu.be/N3c33WKjYV0
- https://www.wsoctv.com/news/local/police-mooresville-man-busted-child-sex-sting/334803464/
