= Perl `pae`, `ppae`, `ppie`

_Monday, January 6, 2025, 6:31:06PM EST_

> POSIX or Perl!

A lot of people don't know that `sed -i` and `awk -i` are _not_ POSIX compliant and should never be used in any scripts, ever. Besides these stupid commands use up more than three times the RAM of `perl` and don't come close to providing the same functionality. Here's how you never use horrible `sed`, `awk`, `tr` and non-POSIX inplace replacements ever again.

I have created three similarly named shell scripts that call `perl` to progressively built up whatever it is I want to transform about a file or text pipeline.

== `pae`

[source,perl]
----
include::../../dot/scripts/pae[]
----

This one maps over each line of input splitting the fields into `@F` but not printing the output without adding a `say` or `print`:

[source,shell]
----
pae print <file>
pae 'say $F[2]' <file>
pae '$x += $F[3];END{say $x}' <file>
----

This is particularly useful for doing things with the line without printing the line, the sort of _reduce_ operations from functional programming. Something similar to this can be done in `awk` but with only a tiny fraction of the power and more than triple the RAM cost.

== `ppae`

This is exactly the same as `pae` but always prints the line after it has been transformed by whatever code is passed as the first argument. Notice that it is capital `E` instead of lower case. This is important because it enables all the optional features like the `say` command, which you _definitely_ want:

[source,perl]
----
include::../../dot/scripts/ppae[]
----

To start a transformation I start with a no-op (`_`) which effectively cats the file to see what I'm dealing with and then change to a transformation:

[source,shell]
----
ppae _ <file>
ppae s,/home,/other/home,g <file>
----

Notice I don't even need to quote the regex most of the time.

This is great for complex filter transformations from within Vim or Neovim when the limited builtin "enhanced" regular expressions just won't cut it (literally).

== `ppie`

Then we have the in-place edit version:

[source,perl]
----
include::../../dot/scripts/ppie[]
----

Here's where the _real_ power kicks in. If I change the `a` to an `i` it will _commit the change to the file_ rather than printing it out:

[source,shell]
----
ppie s,/home,/other/home,g <file>
----

Keep in mind _this is destructive with no backups_. If you are paranoid you can alter the `ppie` program and add a suffix to the `-i` option—perhaps even the process ID—so that you have a backup but I find cleaning up the backups annoying and using the `ppae` first ensures I can preview exactly what the transformation will be in advance. Plus, there's always `git restore`.

Also know that if you enable expanded globbing with `shopt -s globstar` you can use `pass:[**/*.go]` and such to find and replace that _in every single file in the current directory and below_ (yeah, you definitely want that saved with `git commit` first).

== Conclusion

Perl pipelines and filters like these are a _testament to the raw power of text processing in the terminal_ and specifically to Perl. Larry Wall regularly talked about how these transformations were the very reason he created Perl in the first place, not to be better than C and POSIX shell for backend web development, the only options at the time. Forget about bloated extensions and plugins—these one-liners replace them all. And remember, this power _is_ Perl's sweetest of spots. Python, Ruby, Node, Bash, none of them can touch it (and yet all of them use Perl's original regular expressions).
